# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
    config.vm.box_check_update = false
    config.vm.hostname = "ebpf-deb"
    # config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222
    config.vm.synced_folder "../data", "/vagrant_data"
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "ebpf-debian"
        vb.gui = false
        vb.memory = "1024"
        vb.cpus = "2"
    end
  
    config.vm.provision "shell", inline: <<-SHELL
        # Update Package Repository
        apt update
  
        # Setup libbpf
        apt install clang gcc-multilib libbpf-dev -y
  
        # Setup libxdp
        apt install libxdp-dev -y
  
        # Setup bpftool
        apt install wget -y
        wget https://github.com/libbpf/bpftool/releases/download/v7.4.0/bpftool-v7.4.0-amd64.tar.gz
        tar -xzf bpftool-v7.4.0-amd64.tar.gz
        install -m 755 bpftool /usr/sbin
        rm -rf bpftool-v7.4.0-amd64.tar.gz bpftool
    SHELL
end
