# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/fedora39" # "generic/fedora40" not available as of now
    config.vm.box_check_update = false
    config.vm.hostname = "ebpf-fedora"
    # config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222
    config.vm.synced_folder "../../.", "/home/ebpf-playground"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "ebpf-fedora"
        vb.gui = false
        vb.memory = "1024"
        vb.cpus = "2"
    end

    config.vm.provision "shell", inline: <<-SHELL
        # Setup libbpf
        dnf install clang libbpf libbpf-devel -y

        # Setup libxdp
        dnf install libxdp libxdp-devel -y

        # Setup bpftool
        dnf install bpftool -y

        # Setup bpftrace
        dnf install bpftrace -y

        # Setup eunomia-bpf
        dnf install clang llvm wget fuse3 -y
        wget https://github.com/eunomia-bpf/eunomia-bpf/releases/latest/download/ecc
        install -m 755 ecc /usr/bin
        rm -rf ecc
        wget https://github.com/eunomia-bpf/eunomia-bpf/releases/latest/download/ecli
        install -m 755 ecli /usr/sbin
        rm -rf ecli
    SHELL
end
